# deploy nodeapp on containers
version: '3.0'

services:

  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - skynet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        
  mongo:
    image: mongo
    ports:
      - "27017"
    volumes:
      - mongovolume:/data/db
    networks:
      - skynet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - skynet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
  
  nodejsapp:
    image: nodeapp:v1
    ports: 
      - "8080:9000"
    networks:
      - skynet  
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mongovolume:

networks:
  skynet: